site_name: My Docs

docs_dir: 'mkdocs'
site_dir: 'docs/static/mkdocs_build'

pages:
  - Introducción: index.md
  - Liquidaciones: Liquidacion.md
  - Agentes: agente.md
  - Administrador Gral.: admin_gral.md
  - Usuarios: usuario.md

theme: readthedocs
