# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('docfile', models.FileField(upload_to='csv/')),
            ],
        ),
        migrations.CreateModel(
            name='LiqFin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saf', models.IntegerField()),
                ('docfile', models.FileField(upload_to='liquidacion_final/')),
            ],
        ),
        migrations.CreateModel(
            name='Pdf572',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.BigIntegerField()),
                ('periodo', models.IntegerField()),
                ('presentacion', models.IntegerField()),
                ('docfile', models.FileField(upload_to='formulario_f572/')),
                ('tipo', models.CharField(max_length=3)),
            ],
        ),
    ]
