# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='docfile',
            field=models.FileField(upload_to='csv/'),
        ),
    ]
