# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.BigIntegerField()),
                ('tipo_doc', models.CharField(choices=[('80', 'Cuit'), ('86', 'Cuil')], max_length=10)),
                ('empliq', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('cuil', models.CharField(max_length=15)),
                ('f572', models.IntegerField()),
                ('fecha_f572', models.DateField()),
                ('fecha_aplic', models.DateField()),
                ('observ', models.CharField(max_length=255)),
                ('revisado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.IntegerField()),
                ('cp', models.CharField(max_length=8)),
                ('localidad', models.CharField(max_length=60)),
                ('calle', models.CharField(max_length=40)),
                ('nro', models.CharField(max_length=6)),
                ('piso', models.CharField(max_length=5)),
                ('dpto', models.CharField(max_length=5)),
                ('extra', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='agente',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Direccion'),
        ),
    ]
