# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='empliq',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='f572',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_aplic',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_f572',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='observ',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='revisado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='sexo',
        ),
    ]
