# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_administrador_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='empresa',
        ),
    ]
