# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabliq',
            fields=[
                ('liqnro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('indice', models.IntegerField()),
                ('descrip', models.CharField(max_length=50)),
                ('cierre', models.DateField()),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.Mes')),
            ],
        ),
        migrations.AlterField(
            model_name='hliquidac',
            name='nro_liq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.Cabliq'),
        ),
    ]
