# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_administrador_empresa'),
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='administrador_Responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Administrador'),
        ),
    ]
