# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liqfin',
            name='DESCRIP',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
