# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0002_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
